#pragma once
#include <string>

namespace snailRegression
{
	const std::string AVERAGE_OUTPUT_REGRESSION		= "AVERAGE_OUTPUT_REGRESSION";
	const std::string LEAST_SQUARES_REGRESSION		= "LEAST_SQUARES_REGRESSION";
	const std::string FORWARD_STEPWISE_REGRESSION	= "FORWARD_STEPWISE_REGRESSION";
	const std::string FORWARD_STAGEWISE_REGRESSION	= "FORWARD_STAGEWISE_REGRESSION";
}